(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/uni-nav-bar/uni-nav-bar"],{"001e":function(e,n,t){},"1a36":function(e,n,t){"use strict";t.r(n);var a=t("571b"),o=t.n(a);for(var i in a)"default"!==i&&function(e){t.d(n,e,(function(){return a[e]}))}(i);n["default"]=o.a},"571b":function(e,n,t){"use strict";(function(e){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var a=o(t("bf9d"));function o(e){return e&&e.__esModule?e:{default:e}}var i={mixins:[a.default],props:{title:{type:String,default:""},navGosearch:{type:[Boolean,String],default:!1},navOpentab:{type:[Boolean,String],default:!1},navGoback:{type:[Boolean,String],default:!1},navActive:{type:[Boolean,String],default:!1},statusBar:{type:[Boolean,String],default:!1},iconColor:{type:String,default:""},isindex:{type:Boolean,default:!1},isshare:{type:String,default:"0"}},mounted:function(){},methods:{openWrapTab:function(){this.$emit("openWrapTab")},searchClick:function(){e.navigateTo({url:"/pagesA/search/search"})},onShareAppMessage:function(){return{title:this.beebeeos.acf.mode_common.site.name?this.beebeeos.acf.mode_common.site.name:"小程序",path:"/pages/index/index?footerindex=0&categoryindex=0"}}}};n.default=i}).call(this,t("543d")["default"])},8737:function(e,n,t){"use strict";t.r(n);var a=t("98b9"),o=t("1a36");for(var i in o)"default"!==i&&function(e){t.d(n,e,(function(){return o[e]}))}(i);t("efe8");var u,r=t("f0c5"),c=Object(r["a"])(o["default"],a["b"],a["c"],!1,null,"14739546",null,!1,a["a"],u);n["default"]=c.exports},"98b9":function(e,n,t){"use strict";t.d(n,"b",(function(){return o})),t.d(n,"c",(function(){return i})),t.d(n,"a",(function(){return a}));var a={beeIcon:function(){return t.e("components/bee-icon/bee-icon").then(t.bind(null,"33de"))}},o=function(){var e=this,n=e.$createElement;e._self._c},i=[]},efe8:function(e,n,t){"use strict";var a=t("001e"),o=t.n(a);o.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/uni-nav-bar/uni-nav-bar-create-component',
    {
        'components/uni-nav-bar/uni-nav-bar-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("8737"))
        })
    },
    [['components/uni-nav-bar/uni-nav-bar-create-component']]
]);
