(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/uni-popup/uni-popup"],{"04b3":function(t,n,i){"use strict";var e=i("50ac"),o=i.n(e);o.a},"2d8e":function(t,n,i){"use strict";i.d(n,"b",(function(){return o})),i.d(n,"c",(function(){return a})),i.d(n,"a",(function(){return e}));var e={uniTransition:function(){return i.e("components/uni-transition/uni-transition").then(i.bind(null,"4703"))}},o=function(){var t=this,n=t.$createElement;t._self._c},a=[]},"50ac":function(t,n,i){},7179:function(t,n,i){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var e=function(){i.e("components/uni-transition/uni-transition").then(function(){return resolve(i("4703"))}.bind(null,i)).catch(i.oe)},o={name:"UniPopup",components:{uniTransition:e},props:{animation:{type:Boolean,default:!0},type:{type:String,default:"center"},maskClick:{type:Boolean,default:!0},hideMask:{type:Boolean,default:!1},stopTouchMove:{type:Boolean,default:!0},newsss:{type:String,default:"bg bgfilter5"},zIndex:{type:Number,default:200}},data:function(){return{pengyouquantip:!1,duration:300,ani:[],showPopup:!1,showTrans:!1,maskClass:{position:"fixed",bottom:0,top:0,left:0,right:0},transClass:{position:"fixed",left:0,right:0,display:"none"}}},watch:{type:{handler:function(t){switch(this.type){case"top":this.ani=["slide-top"],this.transClass={position:"fixed",top:0,left:0,right:0,bottom:"auto"};break;case"bottom":this.ani=["slide-bottom"],this.transClass={position:"fixed",left:0,right:0,bottom:0,top:"auto"};break;case"center":this.ani=["zoom-out","fade"],this.transClass={position:"fixed",display:"flex",flexDirection:"column",bottom:0,left:0,right:0,top:0,justifyContent:"center",alignItems:"center"};break}},immediate:!0}},created:function(){this.animation?this.duration=300:this.duration=0},methods:{clear:function(t){t.stopPropagation()},open:function(){var t=this;this.showPopup=!0,this.$nextTick((function(){clearTimeout(t.timer),t.timer=setTimeout((function(){t.showTrans=!0}),50)})),this.$emit("change",{show:!0})},close:function(t){var n=this;this.showTrans=!1,this.$nextTick((function(){clearTimeout(n.timer),n.timer=setTimeout((function(){n.$emit("change",{show:!1,pengyouquantip:!1}),n.showPopup=!1,n.pengyouquantip=!1}),300)}))},onTap:function(){this.maskClick&&this.close()},showTip:function(){this.pengyouquantip=!0}}};n.default=o},"8bf9":function(t,n,i){"use strict";i.r(n);var e=i("2d8e"),o=i("ee9a");for(var a in o)"default"!==a&&function(t){i.d(n,t,(function(){return o[t]}))}(a);i("04b3");var s,u=i("f0c5"),r=Object(u["a"])(o["default"],e["b"],e["c"],!1,null,"1836e1f0",null,!1,e["a"],s);n["default"]=r.exports},ee9a:function(t,n,i){"use strict";i.r(n);var e=i("7179"),o=i.n(e);for(var a in e)"default"!==a&&function(t){i.d(n,t,(function(){return e[t]}))}(a);n["default"]=o.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/uni-popup/uni-popup-create-component',
    {
        'components/uni-popup/uni-popup-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("8bf9"))
        })
    },
    [['components/uni-popup/uni-popup-create-component']]
]);
